### PR TITLE
Readme and .gitignore updated

### PR DESCRIPTION
**Pull request by Seqway**
Readme updated according to installation on all systems (Linux, MacOS; Win) and .gitignore modified for excluding .DS_Store files (mainly for MacOS users)

### CODE REVIEW

**Comment by Apollon77** [comment]
Why the link needs these icons? why not simpyl use normal MD options for numbered and unnumbered lists?

**Comment by Seqway** [comment]
I thought this is standard MD feature. But if it should be removed i can change it, no problem.

**Comment by Apollon77** [comment]
Yes it is ... but nothing else on the page uses it :-)

**Comment by GermanBluefox** [comment]
Thank you!

**Pull request merged**
